### ISSUE TITLE
初始化脚本执行完成后没有正常退出，需要手动退出

### ISSUE THREAD

**Issue by alphatr** [75team/thinkjs-cmd#1]
在 shell 中执行初始化脚本，执行完成后没有正常退出，需要手动 Ctrl+C 退出

**Comment by lizheming** [comment]
Windows 平台的 CLI bug，之前找了一下，似乎是底层模板脚手架的bug，后续就没跟进这块了。如果有空的话可以帮忙调一下😂

**Comment by lizheming** [comment]
我去，2015年的bug了么😂还以为是刚提的

**Comment by alphatr** [comment]
时间线上一直存在着太久了，就手动关了😂。。。
